/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_CCPiAccessibleVolume_WRAP_H_
#define SWIG_CCPiAccessibleVolume_WRAP_H_

class SwigDirector_CCPiUserApplicationInterface : public CCPiUserApplicationInterface, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CCPiUserApplicationInterface(JNIEnv *jenv);
    virtual void LogMessage(std::string message);
    virtual void SetStatusMessage(std::string message);
    virtual void SetProgressValue(float value);
    virtual bool isCancel();
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    bool swig_override[4];
};


#endif
