/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_itk__ImageT_unsigned_char_3_t__Pointer {
  private long swigCPtr;

  protected SWIGTYPE_p_itk__ImageT_unsigned_char_3_t__Pointer(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_itk__ImageT_unsigned_char_3_t__Pointer() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_itk__ImageT_unsigned_char_3_t__Pointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

