/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCPiLabelQuantificationResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCPiLabelQuantificationResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCPiLabelQuantificationResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCPiAccessibleVolumeJNI.delete_CCPiLabelQuantificationResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CCPiLabelQuantificationResult() {
    this(CCPiAccessibleVolumeJNI.new_CCPiLabelQuantificationResult(), true);
  }

  public StringVector GetQuantityNames() {
    return new StringVector(CCPiAccessibleVolumeJNI.CCPiLabelQuantificationResult_GetQuantityNames(swigCPtr, this), true);
  }

  public void SetValue(String quantityName, int labelIndex, double value) {
    CCPiAccessibleVolumeJNI.CCPiLabelQuantificationResult_SetValue(swigCPtr, this, quantityName, labelIndex, value);
  }

  public double GetValue(String quantityName, int labelIndex) {
    return CCPiAccessibleVolumeJNI.CCPiLabelQuantificationResult_GetValue(swigCPtr, this, quantityName, labelIndex);
  }

  public IntList GetLabelIndexes() {
    return new IntList(CCPiAccessibleVolumeJNI.CCPiLabelQuantificationResult_GetLabelIndexes(swigCPtr, this), true);
  }

}
