
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sn65
 */
public class CCPiAccessibleVolumeInputDialog extends java.awt.Dialog {

    /**
     * Creates new form CCPiAccessibleVolumeInputDialog
     */
    public CCPiAccessibleVolumeInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isCancelButtonPressed = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        maxSphereDiameter = new javax.swing.JTextField();
        numberOfSpheres = new javax.swing.JTextField();
        imageResolution = new javax.swing.JTextField();
        minSphereDiameter = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Accessible Volume Input");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 50));
        jPanel1.setNextFocusableComponent(jComboBox1);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 180));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        jPanel1Layout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        jPanel1.setLayout(jPanel1Layout);

        jComboBox1.setNextFocusableComponent(jTextField1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jComboBox1, gridBagConstraints);

        maxSphereDiameter.setMinimumSize(new java.awt.Dimension(30, 20));
        maxSphereDiameter.setName("maxSphereDiameter");
        maxSphereDiameter.setNextFocusableComponent(numberOfSpheres);
        maxSphereDiameter.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        jPanel1.add(maxSphereDiameter, gridBagConstraints);

        numberOfSpheres.setMinimumSize(new java.awt.Dimension(30, 20));
        numberOfSpheres.setName("numberOfSpheres");
        numberOfSpheres.setNextFocusableComponent(imageResolution);
        numberOfSpheres.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel1.add(numberOfSpheres, gridBagConstraints);

        imageResolution.setMinimumSize(new java.awt.Dimension(30, 20));
        imageResolution.setName("imageResolution");
        imageResolution.setNextFocusableComponent(jButton1);
        imageResolution.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel1.add(imageResolution, gridBagConstraints);

        minSphereDiameter.setMinimumSize(new java.awt.Dimension(30, 20));
        minSphereDiameter.setName("minSphereDiameter");
        minSphereDiameter.setNextFocusableComponent(maxSphereDiameter);
        minSphereDiameter.setPreferredSize(new java.awt.Dimension(30, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel1.add(minSphereDiameter, gridBagConstraints);

        jTextField1.setColumns(1);
        jTextField1.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField1.setName("");
        jTextField1.setNextFocusableComponent(jButton3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jTextField1, gridBagConstraints);

        jButton3.setText("Browse");
        jButton3.setNextFocusableComponent(minSphereDiameter);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jButton3, gridBagConstraints);

        jButton1.setText("OK");
        jButton1.setNextFocusableComponent(jButton2);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 10;
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setText("Cancel");
        jButton2.setNextFocusableComponent(jComboBox1);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jButton2, gridBagConstraints);

        jLabel1.setText("Mask Image");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Output File");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Number Of Spheres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Image Resolution");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Min/Max Sphere Diameter (um)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV File","csv");
        jfc.setFileFilter(filter);
        int retval = jfc.showSaveDialog(this);
        if(retval == JFileChooser.APPROVE_OPTION)
            jTextField1.setText(jfc.getSelectedFile().getAbsolutePath());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public boolean isCancelButtonPressed(){
        return isCancelButtonPressed;
    }
    
    String getOutputFileName()
    {
        return jTextField1.getText();
    }
    
    String getMaskFileName()
    {
        return jComboBox1.getSelectedItem().toString();
    }
    
    void addMaskFileName(String name)
    {
        jComboBox1.addItem(name);
    }
    
    double getMinSphereDiameter()
    {
        return Double.parseDouble(minSphereDiameter.getText());
    }

    double getMaxSphereDiameter()
    {
        return Double.parseDouble(maxSphereDiameter.getText());
    }

    double getImageResolution()
    {
        return Double.parseDouble(imageResolution.getText());
    }    
    
    int getNumberOfSpheres()
    {
        return Integer.parseInt(numberOfSpheres.getText());
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().compareTo("")!=0)
        {
            
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        isCancelButtonPressed = true; 
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CCPiAccessibleVolumeInputDialog dialog = new CCPiAccessibleVolumeInputDialog(new java.awt.Frame(), true);
                dialog.addMaskFileName("Mask128.raw");                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private boolean isCancelButtonPressed;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField imageResolution;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField maxSphereDiameter;
    private javax.swing.JTextField minSphereDiameter;
    private javax.swing.JTextField numberOfSpheres;
    // End of variables declaration//GEN-END:variables
}
