/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCPiUserApplicationInterface {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCPiUserApplicationInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCPiUserApplicationInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCPiAccessibleVolumeJNI.delete_CCPiUserApplicationInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_change_ownership(this, swigCPtr, true);
  }

  public void LogMessage(String message) {
    CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_LogMessage(swigCPtr, this, message);
  }

  public void SetStatusMessage(String message) {
    CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_SetStatusMessage(swigCPtr, this, message);
  }

  public void SetProgressValue(float value) {
    CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_SetProgressValue(swigCPtr, this, value);
  }

  public boolean isCancel() {
    return CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_isCancel(swigCPtr, this);
  }

  public CCPiUserApplicationInterface() {
    this(CCPiAccessibleVolumeJNI.new_CCPiUserApplicationInterface(), true);
    CCPiAccessibleVolumeJNI.CCPiUserApplicationInterface_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
