/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CCPiLabelQuantificationITKImplUnsignedChar {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CCPiLabelQuantificationITKImplUnsignedChar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CCPiLabelQuantificationITKImplUnsignedChar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CCPiAccessibleVolumeJNI.delete_CCPiLabelQuantificationITKImplUnsignedChar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CCPiLabelQuantificationITKImplUnsignedChar(CCPiImageDataUnsignedChar data, CCPiUserApplicationInterface userAppInterface, float[] origin, int[] volumeDims, float[] voxelSize, float min, float max, float minFeatureSize, int vtkDataType) {
    this(CCPiAccessibleVolumeJNI.new_CCPiLabelQuantificationITKImplUnsignedChar(CCPiImageDataUnsignedChar.getCPtr(data), data, CCPiUserApplicationInterface.getCPtr(userAppInterface), userAppInterface, origin, volumeDims, voxelSize, min, max, minFeatureSize, vtkDataType), true);
  }

  public void Compute() {
    CCPiAccessibleVolumeJNI.CCPiLabelQuantificationITKImplUnsignedChar_Compute(swigCPtr, this);
  }

  public CCPiLabelQuantificationResult GetOutput() {
    long cPtr = CCPiAccessibleVolumeJNI.CCPiLabelQuantificationITKImplUnsignedChar_GetOutput(swigCPtr, this);
    return (cPtr == 0) ? null : new CCPiLabelQuantificationResult(cPtr, false);
  }

}
