# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CCPi', [dirname(__file__)])
        except ImportError:
            import _CCPi
            return _CCPi
        if fp is not None:
            try:
                _mod = imp.load_module('_CCPi', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CCPi = swig_import_helper()
    del swig_import_helper
else:
    import _CCPi
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _CCPi.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _CCPi.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _CCPi.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _CCPi.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _CCPi.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _CCPi.SwigPyIterator_equal(self, x)

    def copy(self):
        return _CCPi.SwigPyIterator_copy(self)

    def next(self):
        return _CCPi.SwigPyIterator_next(self)

    def __next__(self):
        return _CCPi.SwigPyIterator___next__(self)

    def previous(self):
        return _CCPi.SwigPyIterator_previous(self)

    def advance(self, n):
        return _CCPi.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _CCPi.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _CCPi.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _CCPi.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _CCPi.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _CCPi.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _CCPi.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _CCPi.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _CCPi.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CCPi.FloatVector___nonzero__(self)

    def __bool__(self):
        return _CCPi.FloatVector___bool__(self)

    def __len__(self):
        return _CCPi.FloatVector___len__(self)

    def pop(self):
        return _CCPi.FloatVector_pop(self)

    def __getslice__(self, i, j):
        return _CCPi.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CCPi.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CCPi.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CCPi.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CCPi.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CCPi.FloatVector___setitem__(self, *args)

    def append(self, x):
        return _CCPi.FloatVector_append(self, x)

    def empty(self):
        return _CCPi.FloatVector_empty(self)

    def size(self):
        return _CCPi.FloatVector_size(self)

    def clear(self):
        return _CCPi.FloatVector_clear(self)

    def swap(self, v):
        return _CCPi.FloatVector_swap(self, v)

    def get_allocator(self):
        return _CCPi.FloatVector_get_allocator(self)

    def begin(self):
        return _CCPi.FloatVector_begin(self)

    def end(self):
        return _CCPi.FloatVector_end(self)

    def rbegin(self):
        return _CCPi.FloatVector_rbegin(self)

    def rend(self):
        return _CCPi.FloatVector_rend(self)

    def pop_back(self):
        return _CCPi.FloatVector_pop_back(self)

    def erase(self, *args):
        return _CCPi.FloatVector_erase(self, *args)

    def __init__(self, *args):
        this = _CCPi.new_FloatVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _CCPi.FloatVector_push_back(self, x)

    def front(self):
        return _CCPi.FloatVector_front(self)

    def back(self):
        return _CCPi.FloatVector_back(self)

    def assign(self, n, x):
        return _CCPi.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _CCPi.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _CCPi.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _CCPi.FloatVector_reserve(self, n)

    def capacity(self):
        return _CCPi.FloatVector_capacity(self)
    __swig_destroy__ = _CCPi.delete_FloatVector
    __del__ = lambda self: None
FloatVector_swigregister = _CCPi.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _CCPi.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CCPi.StringVector___nonzero__(self)

    def __bool__(self):
        return _CCPi.StringVector___bool__(self)

    def __len__(self):
        return _CCPi.StringVector___len__(self)

    def pop(self):
        return _CCPi.StringVector_pop(self)

    def __getslice__(self, i, j):
        return _CCPi.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CCPi.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CCPi.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CCPi.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CCPi.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CCPi.StringVector___setitem__(self, *args)

    def append(self, x):
        return _CCPi.StringVector_append(self, x)

    def empty(self):
        return _CCPi.StringVector_empty(self)

    def size(self):
        return _CCPi.StringVector_size(self)

    def clear(self):
        return _CCPi.StringVector_clear(self)

    def swap(self, v):
        return _CCPi.StringVector_swap(self, v)

    def get_allocator(self):
        return _CCPi.StringVector_get_allocator(self)

    def begin(self):
        return _CCPi.StringVector_begin(self)

    def end(self):
        return _CCPi.StringVector_end(self)

    def rbegin(self):
        return _CCPi.StringVector_rbegin(self)

    def rend(self):
        return _CCPi.StringVector_rend(self)

    def pop_back(self):
        return _CCPi.StringVector_pop_back(self)

    def erase(self, *args):
        return _CCPi.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _CCPi.new_StringVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _CCPi.StringVector_push_back(self, x)

    def front(self):
        return _CCPi.StringVector_front(self)

    def back(self):
        return _CCPi.StringVector_back(self)

    def assign(self, n, x):
        return _CCPi.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _CCPi.StringVector_resize(self, *args)

    def insert(self, *args):
        return _CCPi.StringVector_insert(self, *args)

    def reserve(self, n):
        return _CCPi.StringVector_reserve(self, n)

    def capacity(self):
        return _CCPi.StringVector_capacity(self)
    __swig_destroy__ = _CCPi.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _CCPi.StringVector_swigregister
StringVector_swigregister(StringVector)

class IntList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntList, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _CCPi.IntList_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CCPi.IntList___nonzero__(self)

    def __bool__(self):
        return _CCPi.IntList___bool__(self)

    def __len__(self):
        return _CCPi.IntList___len__(self)

    def pop(self):
        return _CCPi.IntList_pop(self)

    def __getslice__(self, i, j):
        return _CCPi.IntList___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CCPi.IntList___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CCPi.IntList___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CCPi.IntList___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CCPi.IntList___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CCPi.IntList___setitem__(self, *args)

    def append(self, x):
        return _CCPi.IntList_append(self, x)

    def empty(self):
        return _CCPi.IntList_empty(self)

    def size(self):
        return _CCPi.IntList_size(self)

    def clear(self):
        return _CCPi.IntList_clear(self)

    def swap(self, v):
        return _CCPi.IntList_swap(self, v)

    def get_allocator(self):
        return _CCPi.IntList_get_allocator(self)

    def begin(self):
        return _CCPi.IntList_begin(self)

    def end(self):
        return _CCPi.IntList_end(self)

    def rbegin(self):
        return _CCPi.IntList_rbegin(self)

    def rend(self):
        return _CCPi.IntList_rend(self)

    def pop_back(self):
        return _CCPi.IntList_pop_back(self)

    def erase(self, *args):
        return _CCPi.IntList_erase(self, *args)

    def __init__(self, *args):
        this = _CCPi.new_IntList(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _CCPi.IntList_push_back(self, x)

    def front(self):
        return _CCPi.IntList_front(self)

    def back(self):
        return _CCPi.IntList_back(self)

    def assign(self, n, x):
        return _CCPi.IntList_assign(self, n, x)

    def resize(self, *args):
        return _CCPi.IntList_resize(self, *args)

    def insert(self, *args):
        return _CCPi.IntList_insert(self, *args)

    def pop_front(self):
        return _CCPi.IntList_pop_front(self)

    def push_front(self, x):
        return _CCPi.IntList_push_front(self, x)

    def reverse(self):
        return _CCPi.IntList_reverse(self)
    __swig_destroy__ = _CCPi.delete_IntList
    __del__ = lambda self: None
IntList_swigregister = _CCPi.IntList_swigregister
IntList_swigregister(IntList)

class CCPiSimpleHistogramThresholdingITKImplUnsignedChar(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CCPiSimpleHistogramThresholdingITKImplUnsignedChar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CCPiSimpleHistogramThresholdingITKImplUnsignedChar, name)
    __repr__ = _swig_repr

    def __init__(self, inputImage, volumeDims, voxelSize, origin, minIntensity, maxIntensity):
        this = _CCPi.new_CCPiSimpleHistogramThresholdingITKImplUnsignedChar(inputImage, volumeDims, voxelSize, origin, minIntensity, maxIntensity)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Compute(self):
        return _CCPi.CCPiSimpleHistogramThresholdingITKImplUnsignedChar_Compute(self)

    def GetOutputImage(self, *args):
        return _CCPi.CCPiSimpleHistogramThresholdingITKImplUnsignedChar_GetOutputImage(self, *args)

    def GetPeaks(self):
        return _CCPi.CCPiSimpleHistogramThresholdingITKImplUnsignedChar_GetPeaks(self)
    __swig_destroy__ = _CCPi.delete_CCPiSimpleHistogramThresholdingITKImplUnsignedChar
    __del__ = lambda self: None
CCPiSimpleHistogramThresholdingITKImplUnsignedChar_swigregister = _CCPi.CCPiSimpleHistogramThresholdingITKImplUnsignedChar_swigregister
CCPiSimpleHistogramThresholdingITKImplUnsignedChar_swigregister(CCPiSimpleHistogramThresholdingITKImplUnsignedChar)

# This file is compatible with both classic and new-style classes.


