package:
  name: ccpi-quantification
  version: "0.9"


build:
  preserve_egg_dir: False
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    - boost ==1.64
    - boost-cpp ==1.64
    - cython
    - itk ==4.11.1
    - vtk >=7.1

  run:
    - python
    - numpy
    - boost ==1.64
    - itk ==4.11.1
    - vtk >=7.1
	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
